# Generated by Django 3.0.5 on 2020-04-17 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beach_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Тип пляжа')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Страна')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Тип питания')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Название')),
                ('price', models.IntegerField(help_text='Цена указывается за сутки', verbose_name='Стоимость проживания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='hotel_posters/', verbose_name='Главное фото')),
                ('url', models.SlugField(max_length=150, unique=True)),
                ('beach_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourAgency.Beach_type', verbose_name='Тип пляжа')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourAgency.Country', verbose_name='Страна')),
                ('food_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourAgency.Food_type', verbose_name='Тип питания')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Тип отеля')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tourAgency.Hotel')),
                ('wifi', models.BooleanField(default=False, verbose_name='Wi-fi')),
                ('conditioner', models.BooleanField(default=False, verbose_name='Кондиционер в номере')),
                ('swimming_pool', models.BooleanField(default=False, verbose_name='Бассейн')),
                ('waterslides', models.BooleanField(default=False, verbose_name='Водные горки')),
                ('spa', models.BooleanField(default=False, verbose_name='SPA-центр')),
                ('gym', models.BooleanField(default=False, verbose_name='Спортзал')),
                ('disco', models.BooleanField(default=False, verbose_name='Дискотека')),
                ('car_rental', models.BooleanField(default=False, verbose_name='Прокат авто')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Аноним', max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(default='example@inbox.ru', max_length=254, verbose_name='E-mail')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourAgency.Hotel', verbose_name='Отель')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('days_number', models.IntegerField(verbose_name='Количество дней')),
                ('persons_number', models.IntegerField(verbose_name='Количество человек')),
                ('food_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourAgency.Food_type', verbose_name='Тип питания')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourAgency.Hotel', verbose_name='Отель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='hotel_photos/', verbose_name='Фотография')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourAgency.Hotel', verbose_name='Отель')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourAgency.Hotel_type', verbose_name='Тип отеля'),
        ),
        migrations.CreateModel(
            name='Food_in_hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourAgency.Food_type', verbose_name='Тип питания')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourAgency.Hotel', verbose_name='Отель')),
            ],
        ),
    ]
