# Generated by Django 3.0.5 on 2020-04-17 19:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourAgency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_in_hotel',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='Стоимость питания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='departure_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата вылета'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.PositiveIntegerField(help_text='Цена указывается за сутки', verbose_name='Стоимость проживания'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='days_number',
            field=models.PositiveIntegerField(verbose_name='Количество дней'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='persons_number',
            field=models.PositiveIntegerField(verbose_name='Количество человек'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='services',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tourAgency.Hotel', verbose_name='Отель'),
        ),
    ]
